trigger: none
pool:
  vmImage: "ubuntu-latest"

variables:
- group: AZLZ-Variables

jobs:
- job: Validate
  displayName: Terraform Validate
  pool:
    vmImage: ubuntu-latest
  steps:
  - checkout: self
  
  - task: TerraformInstaller@0
    inputs:
      terraformVersion: 'latest'
  - task: TerraformTaskV2@2
    displayName: 'Terraform : Init'
    inputs:
      provider: 'azurerm'
      command: 'init'
      backendServiceArm: 'Shail-Subs'
      backendAzureRmResourceGroupName: '$(sa-resource_group)'
      backendAzureRmStorageAccountName: '$(storage_accounts)'
      backendAzureRmContainerName: '$(blob_storage)'
      backendAzureRmKey: '$(tfstate_file)'
  - task: TerraformTaskV2@2
    displayName: 'Terraform : Validate'
    inputs:
      command: validate

- job: Deploy
  dependsOn:
  - Validate
  displayName: Terraform Deploy
  pool:
    vmImage: ubuntu-latest
  steps:
  - checkout: self
  - task: TerraformInstaller@0
    displayName: Install Terraform latest
  - task: TerraformTaskV2@2
    displayName: 'Terraform : Init'
    inputs:
      provider: 'azurerm'
      command: 'init'
      workingDirectory: '$(System.DefaultWorkingDirectory)/cluster/landingzone'
      backendServiceArm: 'Shail-Subs'
      backendAzureRmResourceGroupName: '$(sa-resource_group)'
      backendAzureRmStorageAccountName: '$(storage_accounts)'
      backendAzureRmContainerName: '$(blob_storage)'
      backendAzureRmKey: '$(tfstate_file)'
  - task: TerraformTaskV3@3
    displayName: 'Terraform : Plan'
    inputs:
      provider: 'azurerm'
      command: 'plan'
      workingDirectory: '$(System.DefaultWorkingDirectory)/cluster/landingzone'
      commandOptions: '-var-file=$(System.DefaultWorkingDirectory)/cluster/terraform.tfvars'
      environmentServiceNameAzureRM: 'Shail-Subs'
  - task: TerraformTaskV3@3
    displayName: 'Terraform : Apply'
    inputs:
      provider: 'azurerm'
      command: 'apply'
      workingDirectory: '$(System.DefaultWorkingDirectory)/cluster/landingzone'
      commandOptions: '-var-file=$(System.DefaultWorkingDirectory)/cluster/terraform.tfvars'
      environmentServiceNameAzureRM: 'Shail-Subs'